# Creating a Multiple Linear regression Model

In [2]:
# importing required libraries 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# importing a csv file with the boston_house_prices dataset 

df = pd.read_csv('boston_house_prices.csv')

In [4]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [5]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [6]:
# Checking for null values in the dataset

df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [7]:
# assiging the feature and target varibles to the array X,y

X = df[['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT']]
y = df['MEDV']

In [8]:
X

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [9]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: MEDV, Length: 506, dtype: float64

In [10]:
# importing sklearn for train test split

from sklearn.model_selection import train_test_split

In [11]:
# splittinig the dataset into train and test here we are spliting it train 80% and test as 20% , and random state to 3

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [12]:
X_train

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
454,9.51363,0.0,18.10,0,0.7130,6.728,94.1,2.4961,24,666,20.2,6.68,18.71
471,4.03841,0.0,18.10,0,0.5320,6.229,90.7,3.0993,24,666,20.2,395.33,12.87
281,0.03705,20.0,3.33,0,0.4429,6.968,37.2,5.2447,5,216,14.9,392.23,4.59
477,15.02340,0.0,18.10,0,0.6140,5.304,97.3,2.1007,24,666,20.2,349.48,24.91
107,0.13117,0.0,8.56,0,0.5200,6.127,85.2,2.1224,5,384,20.9,387.69,14.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,22.05110,0.0,18.10,0,0.7400,5.818,92.4,1.8662,24,666,20.2,391.45,22.11
131,1.19294,0.0,21.89,0,0.6240,6.326,97.7,2.2710,4,437,21.2,396.90,12.26
249,0.19073,22.0,5.86,0,0.4310,6.718,17.5,7.8265,7,330,19.1,393.74,6.56
152,1.12658,0.0,19.58,1,0.8710,5.012,88.0,1.6102,5,403,14.7,343.28,12.12
362,3.67822,0.0,18.10,0,0.7700,5.362,96.2,2.1036,24,666,20.2,380.79,10.19

In [13]:
X_test

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
224,0.31533,0.0,6.20,0,0.5040,8.266,78.3,2.8944,8,307,17.4,385.05,4.14
137,0.35233,0.0,21.89,0,0.6240,6.454,98.4,1.8498,4,437,21.2,394.08,14.59
453,8.24809,0.0,18.10,0,0.7130,7.393,99.3,2.4527,24,666,20.2,375.87,16.74
303,0.10000,34.0,6.09,0,0.4330,6.982,17.7,5.4917,7,329,16.1,390.43,4.86
254,0.04819,80.0,3.64,0,0.3920,6.108,32.0,9.2203,1,315,16.4,392.89,6.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...
434,13.91340,0.0,18.10,0,0.7130,6.208,95.0,2.2222,24,666,20.2,100.63,15.17
294,0.08199,0.0,13.92,0,0.4370,6.009,42.3,5.5027,4,289,16.0,396.90,10.40
306,0.07503,33.0,2.18,0,0.4720,7.420,71.9,3.0992,7,222,18.4,396.90,6.47
463,5.82115,0.0,18.10,0,0.7130,6.513,89.9,2.8016,24,666,20.2,393.82,10.29
332,0.03466,35.0,6.06,0,0.4379,6.031,23.3,6.6407,1,304,16.9,362.25,7.83

In [14]:
# importing sklearn for Standard Scaler ( we r using this to Standardization the dataset)

from sklearn.preprocessing import StandardScaler

In [15]:
# assigning the StandardScaler to varible scaler

scaler = StandardScaler()

In [16]:
# standardizting the train and test dataset by scaler.fit_trasform  and storing the standardized data to varibles X_train_scaled,X_test_scaled respectively

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [17]:
X_train_scaled

array([[ 0.63193154, -0.48150553,  1.02876713, ...,  0.81181002,
        -3.70131462,  0.81176449],
       [ 0.03051684, -0.48150553,  1.02876713, ...,  0.81181002,
         0.4207414 ,  0.00470343],
       [-0.40900462,  0.41031445, -1.13333814, ..., -1.64542439,
         0.38786253, -1.13955437],
       ...,
       [-0.39212394,  0.49949645, -0.76298429, ...,  0.30181798,
         0.40387772, -0.86730946],
       [-0.28932736, -0.48150553,  1.24541681, ..., -1.73815021,
        -0.13130547, -0.09894311],
       [-0.00904751, -0.48150553,  1.02876713, ...,  0.81181002,
         0.26652889, -0.3656602 ]])

In [18]:
# importing sklearn for linear regression 

from sklearn.linear_model import LinearRegression

In [19]:
# creatng  the regression  model 

model = LinearRegression()

In [20]:
# fitting the train set to the model

model.fit(X_train_scaled,y_train)

LinearRegression()

In [21]:
# performing predictions on  the test data based on the train dataset

model_pred = model.predict(X_test_scaled)

In [22]:
model_pred

array([37.14260061, 18.35614239, 21.17989454, 32.21870346, 23.33540953,
       23.32044586, 18.22590149,  4.44078909, 20.77790204, 16.98399351,
       13.2296065 , 31.56634789, 35.01489458, 30.61564841,  4.30863437,
       10.20874349, 23.11305964, 14.51736213, 12.11115724, 28.72936921,
       26.8146109 , 34.92144398, 26.50709375, 23.79316862, 12.60799937,
       24.75412118, 20.45611223, 18.69442057, 18.97578121, 24.25736008,
       14.18677082, 33.53391986, 20.3984606 , 18.52031755, 19.08142572,
       16.15841375, 20.80303573, 31.90400492, 14.4327431 , 21.63605018,
       16.51731422,  9.38031217, 24.54921945, 16.19173746, 22.84100876,
       25.22948173, 25.7927272 , 17.13325852, 26.97006513, 20.07613493,
       21.83642504, 19.02151266, 37.55264148, 18.1867274 , 22.39852091,
        9.58866431, 35.07790754, 15.58922937, 30.94301131, 19.00974852,
       23.62807002, 21.75558237, 32.56454477, 32.10310319, 19.79802183,
       25.73252179, 33.6540634 , 23.38713316, 28.02281842, 29.88224115,
       24.63167226, 26.50555048, 19.14322242, 30.23667978, 10.06789123,
       22.17517992, 25.16370729, 24.76043145, 22.00263282, 18.30945004,
       26.30893403, 18.56933019,  6.99750255, 19.39632621, 25.95853245,
       12.86169365, 27.10860175, 13.76919746, 21.1682013 , 25.01151963,
       18.56203237, 20.38433204, 21.54963031, 38.3368149 , 30.74424613,
       14.93513423, 41.72405959, 13.93895364, 23.66956792, 34.77339066,
       21.74946441, 23.01227091])

In [23]:
# comparing the acutal (y_test) and predicted values (model_pred) 

y_test

224    44.8
137    17.1
453    17.8
303    33.1
254    21.9
       ...
434    11.7
294    21.7
306    33.4
463    20.2
332    19.4
Name: MEDV, Length: 102, dtype: float64

In [24]:
# importing sklearn for mean squared error 

from sklearn.metrics import mean_squared_error

In [25]:
# finding the mean_squared_error for the acutal and predicted values and storing it in mse

mse = mean_squared_error(y_test,model_pred)

In [26]:
# the mean squared error is 16.94%  so the accuary of the model is 83.06%

mse

16.94953158867413

## Conclusion : mean squared error is 16.94%  so the accuary of the model is 83.06%