## Performing a simple Linear regression Model

In [2]:
# creating a dictorniary with manual entries to test the model 

data = {
    'Area':[1600,1800,2400,3000,3200,3600,4000,4100,4200],
    'Bedroom':[3,4,3,5,4,3,5,4,3],
    'Bathrooms':[2,3,3,4,3,2,4,3,3],
    'Age':[10,5,8,4,6,12,3,7,6],
    'Price':[80,95,120,140,155,75,180,160,110]
}

In [3]:
data

{'Area': [1600, 1800, 2400, 3000, 3200, 3600, 4000, 4100, 4200],
 'Bedroom': [3, 4, 3, 5, 4, 3, 5, 4, 3],
 'Bathrooms': [2, 3, 3, 4, 3, 2, 4, 3, 3],
 'Age': [10, 5, 8, 4, 6, 12, 3, 7, 6],
 'Price': [80, 95, 120, 140, 155, 75, 180, 160, 110]}

In [4]:
# importing pandas to create the manual data into a dataframe

import pandas as pd
df = pd.DataFrame(data)

In [5]:
df

   Area  Bedroom  Bathrooms  Age  Price
0  1600        3          2   10     80
1  1800        4          3    5     95
2  2400        3          3    8    120
3  3000        5          4    4    140
4  3200        4          3    6    155
5  3600        3          2   12     75
6  4000        5          4    3    180
7  4100        4          3    7    160
8  4200        3          3    6    110

In [6]:
# importing sklearn for train test split and linear regression 

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [7]:
# assiging the feature and target varibles to the array X,y

X = df[['Area','Bedroom','Bathrooms','Age']]
y = df['Price']

In [8]:
# splittinig the dataset into train and test here we are spliting it train 80% and test as 20% , and random state to 3

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [9]:
# creatng  the linear regression  model 

model = LinearRegression()

In [10]:
# fitting the train set to the model

model.fit(X_train,y_train)

LinearRegression()

In [11]:
# performing predictions on  the test data

y_pred = model.predict(X_test)

In [12]:
# comparing the acutal and predicted values 

result = pd.DataFrame({'Actual' : y_test, 'Predicted':y_pred})

In [13]:
result

   Actual   Predicted
6     180  184.043026
2     120   23.689947

In [14]:
# calculating accuracy of the model

accuracy = model.score(X_train,y_train)

In [15]:
accuracy

0.8375465061708505

In [16]:
# performing predictions for custom / new entry 

new_house = pd.DataFrame({
    'Area':[3300],
    'Bedroom':[4],
    'Bathrooms':[3],
    'Age':[6]
    
})

In [17]:
predict_new_house = model.predict(new_house)

In [18]:
predict_new_house

array([146.16046102])

## Conclusion : the model has attained more than 80 % accuracy